name: Build CI (Master)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Build with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set ENV
      run: echo "NODE_OPTIONS=--no-experimental-fetch" >> $GITHUB_ENV
    - run: npm ci
    - run: npm run test
    - run: npm run coverage
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
    - name: Unset ENV
      run: echo "NODE_OPTIONS=''" >> $GITHUB_ENV
