on: ["push", "pull_request"]

name: Coveralls

jobs:
  build:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Coverage
      run: npm run coverage
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
