name: ESLint & Prettier

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint code
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - run: npm ci
    - run: npm run lint
